### ISSUE TITLE
optional vimtex dependency

### ISSUE THREAD

**Issue by sharethewisdom** [iurimateus/luasnip-latex-snippets.nvim#1]
Thank you for these ported snippets and the conditional expansion.

I'd like to move on to build more on the (abstracted) features brought to me by the texlab lsp server, treesitter and neovim itself. This duplicates some of the vimtex features. I'd like to therefore remove the vimtex dependency altogether.

Is it, in your opinion, worth the effort to duplicate the utilities borrowed from vimtex and/or would it be bad to provide to users an option to just ignore conditional expansion, or would you like to keep it as-is?

**Comment by iurimateus** [comment]
I've created a branch with treesitter support.
You'll need to call `require("luasnip-latex-snippets").setup({ use_treesitter = true })` to setup the plugin.

Credits/reference: https://github.com/nvim-treesitter/nvim-treesitter/issues/1184#issuecomment-1079844699

I've not tested it thoroughly, so any help with edge cases is appreciated. Let me know what you think.

**Comment by sharethewisdom** [comment]
oh, exciting, that was quick, thanks! :partying_face:

While `:lua =require('luasnip-latex-snippets.util.utils').is_math(true)` and the other functions work correctly, all of the snippets are expanded everywhere. (I never tested with vimtex, and I might be doing something wrong here.)

**Comment by iurimateus** [comment]
Related https://github.com/L3MON4D3/LuaSnip/issues/504

**Comment by iurimateus** [comment]
The condition is only for `autosnippets`. You might want to look into `cmp.mapping.confirm({ select = false })`

**Comment by sharethewisdom** [comment]
https://github.com/jbyuki/nabla.nvim/blob/6c9b85cce615e2f2e371045d85463f9f6ac68634/src/treesitter/detect_mathzone.lua.t#L46-L75

**Comment by iurimateus** [comment]
Treesitter support was added a while ago and seems stable enough, making vimtex optional.
