### ISSUE TITLE
Don't set `condition` after construction

### ISSUE THREAD

**Issue by L3MON4D3** [iurimateus/luasnip-latex-snippets.nvim#14]
Hey!
I noticed that there are a few places where `condition` is set on a snippet after it was constructed. This is not going to work after https://github.com/L3MON4D3/LuaSnip/pull/974 is merged, since `condition` will be implemented inside another, more general function.

I think there are a few nice ways to fix this, for example `extend_decorator`:
```lua
local s = ls.extend_decorator.apply(ls.snippet, {condition = the_condition})

s(...) -- <--- will generate a snippet with condition `the_condition`.
```
(The files may have to expose a function for generating the snippets now, since the condition depends on what is passed in `setup`)
(I'd also recommend doing the same with `trig_matcher`/`trigEngine`, since that also isn't officially supported, and might break in the future)

I tried tackling this myself, but noticed that the change wasn't as trivial as I thought :sweat_smile:
I hope you can work on this soon, I don't want to merge a PR which breaks well-used plugins, but still would like to merge that PR somewhat soon. If you absolutely have no time, I can probably find some.

**Comment by iurimateus** [comment]
Thanks for the notice!

I wasn't aware of `extend_decorator`. I think I can finish it by the end of the week.

**Comment by L3MON4D3** [comment]
Beautiful, looking forward to it :)

**Comment by iurimateus** [comment]
It's messy, but it works for now.

**Comment by L3MON4D3** [comment]
Thank you for taking care of it so quickly!
