### ISSUE TITLE
Optional Extension to Markdown

### ISSUE THREAD

**Issue by vmuthuk2** [iurimateus/luasnip-latex-snippets.nvim#2]
Thank you for a great plugin. Works perfectly.

I was wondering if it would be possible to extend these set of snippets to markdown. I use pandoc to convert markdown and rmarkdown to latex or pdf sometimes and used to use the same set of snippets with Ultisnips.

Following change to plugin options doesn't do the trick. 
```lua
ft = {'tex', 'markdown'},
```
I checked packerstatus inside mardown file to verify if the plugin is loaded.

**Comment by iurimateus** [comment]
Try the [markdown](https://github.com/iurimateus/luasnip-latex-snippets.nvim/tree/markdown). There's probably some snippets that aren't suitable there. Feedback is appreciated.

**Comment by vmuthuk2** [comment]
Thank you. Markdown branch works perfectly. The `beg` keyword at beginning of line still triggers inside markdown but that is fine, I mainly use it for math snippets.

**Comment by meicale** [comment]
Such wonderful work. I just wonder how can it trigger the right branch? Or, how can the neovim detech the right block of the filetype and tried all the mathblock as tex filetype?

**Comment by iurimateus** [comment]
> I just wonder how can it trigger the right branch? Or, how can the neovim detech the right block of the filetype and tried all the mathblock as tex filetype?

It can't detect whether we're in a math block or not. It mostly works by accident right now.
That's why Markdown isn't (yet) supported.

I suppose one could write a tree sitter query or a vim syntax file. Might be worth looking into https://github.com/preservim/vim-markdown#syntax-extensions
