### ISSUE TITLE
Math mode snippets also work in label command inside math environment

### ISSUE THREAD

**Issue by JoostScheffer** [iurimateus/luasnip-latex-snippets.nvim#23]
When I have the following code, and want to make the label `eq:malus1` then this autoexpands to `eq:malus_{1}`.
Is there a way to tell the auto-subscript snippet that it is no longer inside math mode?

```latex
\begin{equation}
    P(\theta ) = P_{0}\cos ^2 \left( \theta  \right)
    \label{eq:malus_{1}} % supposed to be \label{eq:malus1}
\end{equation}
```

When the text environment is used (`\text{malus1}` ) the auto-subscript snipped does not autoexpand. I would like the snippets the `label` command to not get recognised as a math environment and would like similar behavior to the `text` command. Do you know how this can be achieved?

**Comment by iurimateus** [comment]
Thanks for the detailed explanation, I'll take a look at it over the weekend.

**Comment by JoostScheffer** [comment]
:1st_place_medal:  Thank you!
