### ISSUE TITLE
fraction snippet not triggering in markdown

### ISSUE THREAD

**Issue by prashantt492** [iurimateus/luasnip-latex-snippets.nvim#24]
All the `math_iA` snippets are working in markdown except the `//` which triggers `\frac{}{}`. When I change the trigger from `//` to some other command, it works. But what could be the issue with `//`.

Also, the autofraction isn't working.

**Comment by prashantt492** [comment]
Figured it out, it was mainly due to TS markdown, disabling it fixes the issue.

**Comment by eiiot** [comment]
I'm still running into the issue with autofraction

**Comment by iurimateus** [comment]
I can't reproduce...

**Comment by prashantt492** [comment]
> I'm still running into the issue with autofraction

Maybe it's due to any neovim configuration or any plugin, because when I changed my config from `lazyvim` to `kickstart` the issue vanished, even with TSMarkdown.
