### ISSUE TITLE
The snippets are not formated correctly and appear as just one line

### ISSUE THREAD

**Issue by Mattio-cmd** [iurimateus/luasnip-latex-snippets.nvim#26]
Take for instance `vimtex_enumerate`. It comes out like this:
`\begin{enumerate}  \item $0\end{enumerate}`
 
As just one line.

Besides, i dont really thing having it as `vimtex_xxx` is the best idea. At this point just leave it for the specific snippet name.

**Comment by iurimateus** [comment]
I'm pretty sure we aren't defining this snippet.
