### ISSUE TITLE
Some Snippets dont expand

### ISSUE THREAD

**Issue by JonaGTHB** [iurimateus/luasnip-latex-snippets.nvim#27]
Hi, first of i want to say thanks for making this plugin.

The issue I'm facing is the following: 
Some snippets don't expand while some others do. I've written down some examples:

`a1` correctly expands to `a_{1}`
`32/3` correctly expands to `\frac{32}{3}`
`fun` correctly expands to `f \colon  \R \to \R \colon`
Other snippets on the other hand **don't** seem to expand, examples include: 
`sum` which **should** expand to `\sum_{n = 1}^{\infty}` 
`lim` which **should** expand to `\lim_{n \to \infty}`

Funnily enough i can see these snippets in LuaSnip when executing `:LuaSnipListAvailable` which for example shows 
```
    }, {
      description = { "sum" },
      name = "sum",
      regTrig = false,
      trigger = "sum",
      wordTrig = false
    }, {
```

I'd really appreciate some help in fixing this or a heads-up if this is unsupported functionality.

Thanks

P.s
I've attached relevant lua code for configuration.

(in plugins for lazy.nvim)
```
{'iurimateus/luasnip-latex-snippets.nvim', dependencies = {'L3MON4D3/LuaSnip'}},
```

(in nvim/after/plugins/luasnip-latex.lua)
```
require('luasnip-latex-snippets').setup({
    use_treesitter = true,
})
```

(in nvim/after/plugins/luasnip.lua)
```
require('luasnip').config.setup(
    { enable_autosnippets = true })
```

**Comment by iurimateus** [comment]
I think those aren't set to automatically expand, since they might be too disruptive. They should show on completion though, if using e.g. cmp-luasnip.

**Comment by maxdulay** [comment]
Hi, I'm having the same issue but `:LuaSnipListAvailable` does not show any of the snippets that do not automatically expand. For some reason they aren't being added?

**Comment by v0ry** [comment]
**Figured It Out, Here is what I did, what solved it for me!**

Check if the plugin did load. 

> `LuaSnipListAvailable`

Check if it manually expands

> `:lua require'luasnip'.expand()`
> `:message` -- in Lua messages are silenced (often) display error messages

If you use nvim.lazy

`    
{
      "iurimateus/luasnip-latex-snippets.nvim",
      -- vimtex isn't required if using treesitter
      branch = "fix/lazy-loading", -- change the branch
      dependencies = { "L3MON4D3/LuaSnip", "lervag/vimtex" },
      ft = {"tex", "markdown" },
      config = function()
        require'luasnip-latex-snippets'.setup({ use_treesitter = true })
        -- or setup({ use_treesitter = true })
      end,
    },
`

**Comment by v0ry** [comment]
```
      "iurimateus/luasnip-latex-snippets.nvim",
      -- vimtex isn't required if using treesitter
      branch = "fix/lazy-loading",
      dependencies = { "L3MON4D3/LuaSnip", "lervag/vimtex" },
      ft = {"tex", "markdown" },
      config = function()
        require'luasnip-latex-snippets'.setup({ use_treesitter = true })
        -- or setup({ use_treesitter = true })
      end,
```
