### ISSUE TITLE
Auto Completing at the beginning of a line

### ISSUE THREAD

**Issue by diligentlystereotypedinvestment** [iurimateus/luasnip-latex-snippets.nvim#34]
Could you add the feature of an autocomplete only triggering at the beginning of a line? I think it would really enhance the typing experience (begin in a sentence won't mess stuff up, same with cases).

**Comment by iurimateus** [comment]
begin, align and cases are already defined like so

https://github.com/iurimateus/luasnip-latex-snippets.nvim/blob/main/lua/luasnip-latex-snippets/bwA.lua
